from environs import Env

env = Env()
env.read_env()

LOGGING_LEVEL = env.str("LOGGING_LEVEL", "INFO")

APPINSIGHTS_INSTRUMENTATION_KEY = env.str("APPINSIGHTS_INSTRUMENTATION_KEY", None)
AKILI_ENV = env.str("AKILI_ENV", None)

AZURE_CLIENT_ID = env.str("AZURE_CLIENT_ID", None)
AZURE_TENANT_ID = env.str("AZURE_TENANT_ID", None)
AZURE_BLOB_ACCOUNT_NAME = env.str("AZURE_BLOB_ACCOUNT_NAME", None)
AZURE_BLOB_ACCOUNT_KEY = env.str("AZURE_BLOB_ACCOUNT_KEY", None)

COSMOS_DB_ENDPOINT = env.str("COSMOS_DB_ENDPOINT", None)
COSMOS_DB_KEY = env.str("COSMOS_DB_KEY", None)
COSMOS_DB_DATABASE = env.str("COSMOS_DB_DATABASE", None)
COSMOS_DEPLOYMENTS_DB_CONTAINER = env.str("COSMOS_DEPLOYMENTS_DB_CONTAINER", None)
